import type { ReportData, ReportFormat } from "../generator"

export class ExecutiveTemplate {
  render(data: ReportData, format: ReportFormat = "markdown"): string {
    if (format === "markdown") {
      return this.renderMarkdown(data)
    } else if (format === "json") {
      return this.renderJson(data)
    } else if (format === "html") {
      return this.renderHtml(data)
    }
    return this.renderMarkdown(data)
  }

  private renderMarkdown(data: ReportData): string {
    const lines: string[] = []

    lines.push("# Executive Summary")
    lines.push("")
    lines.push(`**Report Generated**: ${new Date().toISOString()}`)
    lines.push(`**Classification**: INTERNAL USE ONLY`)
    lines.push("")

    if (data.operation) {
      lines.push("## Operation Overview")
      lines.push("")
      lines.push(`**Operation Name**: ${data.operation.name}`)
      lines.push(`**Operation Type**: ${data.operation.type}`)
      lines.push(`**Status**: ${this.formatStatus(data.operation.status)}`)
      lines.push(`**Started**: ${data.operation.createdAt.toISOString()}`)
      lines.push("")

      if (data.operation.description) {
        lines.push("**Description**")
        lines.push("")
        lines.push(data.operation.description)
        lines.push("")
      }

      lines.push("## Executive Summary")
      lines.push("")
      lines.push(this.generateExecutiveSummary(data))
      lines.push("")

      lines.push("## Key Achievements")
      lines.push("")
      const completedObjectives = data.operation.objectives.filter((o) => o.completed)
      if (completedObjectives.length > 0) {
        completedObjectives.forEach((obj, idx) => {
          lines.push(`${idx + 1}. ${obj.title}`)
          lines.push(`   ${obj.description}`)
          lines.push("")
        })
      } else {
        lines.push("No objectives completed yet.")
        lines.push("")
      }

      lines.push("## Objectives Status")
      lines.push("")
      lines.push(`**Total Objectives**: ${data.operation.objectives.length}`)
      lines.push(`**Completed**: ${completedObjectives.length}`)
      lines.push(`**Pending**: ${data.operation.objectives.length - completedObjectives.length}`)
      lines.push("")
      lines.push("| Objective | Status |")
      lines.push("|-----------|--------|")
      data.operation.objectives.forEach((obj) => {
        const status = obj.completed ? "✓ Completed" : "○ Pending"
        lines.push(`| ${obj.title} | ${status} |`)
      })
      lines.push("")

      lines.push("## Risk Assessment")
      lines.push("")
      lines.push(this.generateRiskAssessment(data))
      lines.push("")

      lines.push("## Recommendations")
      lines.push("")
      lines.push(this.generateRecommendations(data))
      lines.push("")
    }

    lines.push("## Operational Metrics")
    lines.push("")
    lines.push(this.generateMetrics(data))
    lines.push("")

    lines.push("## Next Steps")
    lines.push("")
    lines.push(this.generateNextSteps(data))
    lines.push("")

    lines.push("---")
    lines.push("")
    lines.push("*This report was automatically generated by the C2 reporting system.*")
    lines.push("*For technical details, refer to the Technical Findings report.*")

    return lines.join("\n")
  }

  private renderJson(data: ReportData): string {
    return JSON.stringify(
      {
        type: "executive_summary",
        generatedAt: new Date().toISOString(),
        classification: "INTERNAL USE ONLY",
        operation: data.operation,
        summary: this.generateExecutiveSummary(data),
        keyAchievements: data.operation?.objectives.filter((o) => o.completed) || [],
        riskAssessment: this.generateRiskAssessment(data),
        recommendations: this.generateRecommendations(data),
        metrics: this.generateMetrics(data),
        nextSteps: this.generateNextSteps(data),
      },
      null,
      2
    )
  }

  private renderHtml(data: ReportData): string {
    let html = `<!DOCTYPE html>
<html>
<head>
  <title>Executive Summary</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #333; border-bottom: 2px solid #333; }
    h2 { color: #555; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #f5f5f5; }
    .status-completed { color: green; }
    .status-pending { color: orange; }
  </style>
</head>
<body>
  <h1>Executive Summary</h1>
  <p><strong>Report Generated:</strong> ${new Date().toISOString()}</p>
  <p><strong>Classification:</strong> INTERNAL USE ONLY</p>
`

    if (data.operation) {
      html += `
  <h2>Operation Overview</h2>
  <p><strong>Operation Name:</strong> ${data.operation.name}</p>
  <p><strong>Operation Type:</strong> ${data.operation.type}</p>
  <p><strong>Status:</strong> ${this.formatStatus(data.operation.status)}</p>
  <p><strong>Started:</strong> ${data.operation.createdAt.toISOString()}</p>
`
      if (data.operation.description) {
        html += `  <p><strong>Description:</strong> ${data.operation.description}</p>`
      }

      html += `
  <h2>Executive Summary</h2>
  <p>${this.generateExecutiveSummary(data)}</p>

  <h2>Key Achievements</h2>
  <ul>
`
      const completedObjectives = data.operation.objectives.filter((o) => o.completed)
      completedObjectives.forEach((obj) => {
        html += `    <li><strong>${obj.title}</strong>: ${obj.description}</li>`
      })
      html += `  </ul>`

      html += `
  <h2>Objectives Status</h2>
  <p><strong>Total Objectives:</strong> ${data.operation.objectives.length}</p>
  <p><strong>Completed:</strong> ${completedObjectives.length}</p>
  <p><strong>Pending:</strong> ${data.operation.objectives.length - completedObjectives.length}</p>
  <table>
    <tr><th>Objective</th><th>Status</th></tr>
`
      data.operation.objectives.forEach((obj) => {
        const statusClass = obj.completed ? "status-completed" : "status-pending"
        const status = obj.completed ? "✓ Completed" : "○ Pending"
        html += `    <tr><td>${obj.title}</td><td class="${statusClass}">${status}</td></tr>`
      })
      html += `  </table>`

      html += `
  <h2>Risk Assessment</h2>
  <p>${this.generateRiskAssessment(data)}</p>

  <h2>Recommendations</h2>
  <p>${this.generateRecommendations(data)}</p>
`
    }

    html += `
  <h2>Operational Metrics</h2>
  <p>${this.generateMetrics(data)}</p>

  <h2>Next Steps</h2>
  <p>${this.generateNextSteps(data)}</p>

  <hr>
  <p><em>This report was automatically generated by the C2 reporting system.</em></p>
  <p><em>For technical details, refer to the Technical Findings report.</em></p>
</body>
</html>`

    return html
  }

  private generateExecutiveSummary(data: ReportData): string {
    if (!data.operation) {
      return "No operation data available for summary."
    }

    const completedObjectives = data.operation.objectives.filter((o) => o.completed)
    const completionRate = data.operation.objectives.length > 0
      ? (completedObjectives.length / data.operation.objectives.length) * 100
      : 0

    const completedTasks = data.operation.tasks.filter((t) => t.status === "completed")
    const taskCompletionRate = data.operation.tasks.length > 0
      ? (completedTasks.length / data.operation.tasks.length) * 100
      : 0

    return `The operation "${data.operation.name}" is currently in ${data.operation.status.toLowerCase()} phase. ` +
      `Objective completion rate is ${completionRate.toFixed(1)}% (${completedObjectives.length}/${data.operation.objectives.length}). ` +
      `Task completion rate is ${taskCompletionRate.toFixed(1)}% (${completedTasks.length}/${data.operation.tasks.length}). ` +
      `${data.beacons?.length || 0} beacons have been established, ` +
      `${data.credentials?.length || 0} credentials have been harvested, and ` +
      `${data.lateralMovements?.length || 0} lateral movements have been executed.`
  }

  private generateRiskAssessment(data: ReportData): string {
    const risks: string[] = []

    if (data.beacons && data.beacons.length > 0) {
      const staleBeacons = data.beacons.filter((b) => {
        const hoursSinceLastSeen = (Date.now() - b.lastSeen.getTime()) / (1000 * 60 * 60)
        return hoursSinceLastSeen > 24
      })
      if (staleBeacons.length > 0) {
        risks.push(`- ${staleBeacons.length} beacons have not checked in within 24 hours (potential detection)`)
      }
    }

    if (data.lateralMovements && data.lateralMovements.length > 0) {
      const failedMovements = data.lateralMovements.filter((m) => m.status === "failed")
      if (failedMovements.length > 0) {
        risks.push(`- ${failedMovements.length} lateral movement attempts have failed (may indicate security controls)`)
      }
    }

    if (risks.length === 0) {
      risks.push("- No significant risks identified at this time")
      risks.push("- Continue monitoring beacon health and detection indicators")
    }

    return risks.join("\n")
  }

  private generateRecommendations(data: ReportData): string {
    const recommendations: string[] = []

    if (!data.operation) {
      recommendations.push("- Select an operation to generate specific recommendations")
    } else {
      const pendingObjectives = data.operation.objectives.filter((o) => !o.completed)
      if (pendingObjectives.length > 0) {
        recommendations.push(`- Focus on completing ${pendingObjectives.length} remaining objectives`)
      }

      const pendingTasks = data.operation.tasks.filter((t) => t.status === "pending")
      if (pendingTasks.length > 0) {
        recommendations.push(`- Prioritize execution of ${pendingTasks.length} pending tasks`)
      }

      if (data.beacons && data.beacons.length > 0) {
        recommendations.push("- Maintain regular beacon check-ins to ensure persistence")
      }

      if (data.credentials && data.credentials.length > 0) {
        const uncracked = data.credentials.filter((c) => !c.cracked)
        if (uncracked.length > 0) {
          recommendations.push(`- Attempt to crack ${uncracked.length} uncracked credentials for lateral movement opportunities`)
        }
      }
    }

    recommendations.push("- Continue monitoring for detection indicators")
    recommendations.push("- Document all findings for final report compilation")

    return recommendations.join("\n")
  }

  private generateMetrics(data: ReportData): string {
    const metrics: string[] = []

    metrics.push(`**Beacons Established**: ${data.beacons?.length || 0}`)
    metrics.push(`**Credentials Harvested**: ${data.credentials?.length || 0}`)
    metrics.push(`**Lateral Movements**: ${data.lateralMovements?.length || 0}`)
    metrics.push(`**Implants Deployed**: ${data.implants?.length || 0}`)

    if (data.operation) {
      metrics.push(`**Objectives**: ${data.operation.objectives.filter((o) => o.completed).length}/${data.operation.objectives.length} completed`)
      metrics.push(`**Tasks**: ${data.operation.tasks.filter((t) => t.status === "completed").length}/${data.operation.tasks.length} completed`)
    }

    return metrics.join("\n")
  }

  private generateNextSteps(data: ReportData): string {
    const steps: string[] = []

    if (data.operation) {
      const pendingTasks = data.operation.tasks.filter((t) => t.status === "pending")
      if (pendingTasks.length > 0) {
        const highPriority = pendingTasks.filter((t) => t.priority === "HIGH")
        if (highPriority.length > 0) {
          steps.push(`1. Execute ${highPriority.length} high-priority pending tasks`)
        }
        steps.push(`2. Continue with remaining ${pendingTasks.length} pending tasks`)
      }

      const pendingObjectives = data.operation.objectives.filter((o) => !o.completed)
      if (pendingObjectives.length > 0) {
        steps.push(`3. Work towards completing ${pendingObjectives.length} remaining objectives`)
      }
    }

    steps.push("4. Maintain operational security and monitor for detection")
    steps.push("5. Document all activities and findings")

    return steps.join("\n")
  }

  private formatStatus(status: string): string {
    const statusMap: Record<string, string> = {
      PLANNING: "Planning Phase",
      ACTIVE: "Active Operation",
      PAUSED: "Paused",
      COMPLETED: "Completed",
      CANCELLED: "Cancelled",
    }
    return statusMap[status] || status
  }
}

export const executiveTemplate = new ExecutiveTemplate()