#!/usr/bin/env bash
# Generate a lucide-react proxy module that only exports canonical icon names.
#
# Turbopack's built-in optimizePackageImports for lucide-react creates broken
# bindings for *Icon aliases (e.g. XIcon, Loader2Icon) and deprecated names
# (e.g. Loader2) because individual icon files only export their canonical
# name as default. The proxy bypasses this by re-exporting only canonical
# names from individual icon files, and Turbopack's resolveAlias redirects
# all lucide-react imports to the proxy.
#
# This script runs on npm postinstall to keep the proxy in sync with the
# installed lucide-react version.

set -euo pipefail

BARREL="node_modules/lucide-react/dist/esm/lucide-react.mjs"
PROXY="lib/lucide-proxy.mjs"

if [ ! -f "$BARREL" ]; then
  echo "Skipping lucide-react proxy generation (barrel not found)"
  exit 0
fi

node -e "
const fs = require('fs');
const barrel = fs.readFileSync('$BARREL', 'utf8');
const lines = barrel.split('\n').filter(l => l.startsWith('export {'));

let reexports = [];
for (const line of lines) {
  const match = line.match(/export\s+\{([^}]+)\}\s+from\s+'([^']+)'/);
  if (!match) continue;
  const names = match[1].split(',').map(n => n.trim().replace(/^default as /, ''));
  const source = match[2];
  // Only keep canonical names: no *Icon suffix, no Lucide* prefix, no Loader2
  const canonical = names.filter(n =>
    !n.endsWith('Icon') &&
    !n.startsWith('Lucide') &&
    n !== 'Loader2'
  );
  if (canonical.length > 0) {
    reexports.push({ names: canonical, source });
  }
}

let output = '// Auto-generated lucide-react proxy — only canonical names, no *Icon aliases\n';
output += '// Regenerated by scripts/patch-lucide.sh on npm postinstall\n';
output += '// DO NOT EDIT — changes will be overwritten\n\n';
for (const r of reexports) {
  // Rewrite ./icons/ paths to lucide-react/dist/esm/icons/ so the proxy
  // can live outside node_modules
  const source = r.source.replace('./icons/', 'lucide-react/dist/esm/icons/')
                         .replace('./context.mjs', 'lucide-react/dist/esm/context.mjs')
                         .replace('./createLucideIcon.mjs', 'lucide-react/dist/esm/createLucideIcon.mjs');
  const exports = r.names.map(n => 'default as ' + n).join(', ');
  output += 'export { ' + exports + \" } from '\" + source + \"';\\n\";
}

fs.writeFileSync('$PROXY', output);
console.log('Generated $PROXY with ' + reexports.length + ' export lines');
"

echo "lucide-react proxy generated successfully"
